apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: iempui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iempui
  template:
    metadata:
      labels:
        app: iempui
    spec:
      containers:
      - name: iempui
        image: kube3acr.azurecr.io/iempui
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: acr-secret
      ports:
      - containerPort: 3000
